### ISSUE TITLE
[question] how about make it compatible with wcjs-renderer?

### ISSUE THREAD

**Issue by RSATom** [tmarrinan/node-demux#3]
please look at https://github.com/RSATom/webgl-video-renderer (it's `wcjs-renderer` without dependency from `WebChimera.js`).
renderer usage example: https://github.com/RSATom/wcjs-ugly-demo

If you will have any questions, or will need help - I (and some other guys) will be glad to help you.

**Comment by smolleyes** [comment]
+1

**Comment by tmarrinan** [comment]
For frame accurate rendering I have implemented a streaming app that sends the frames decoded on the server to a web client via WebSockets. The client then uses these frames as WebGL textures.
*Note: this does require very high bandwidth networks ( > 1 Gbps)

I the websocketio library (https://github.com/tmarrinan/websocketio) that I developed for the streaming. It's very similar to socket.io, but outperforms it for binary streaming.

**Comment by RSATom** [comment]
Did you try something like Full HD with client and server on the same host? Is it possible get good fps?

**Comment by tmarrinan** [comment]
Yes - if server and client are the same (connect to server using localhost), then the framerate is good. It is also good if you have an internal network with > 1 Gbps connecting a server to a client that is on a different machine.
4K videos can get a bit choppy depending on your CPU (decoding time alone comes into play, along with streaming and rendering)

**Comment by RSATom** [comment]
What hardware did you use in this test? What cpu load did you have?

**Comment by tmarrinan** [comment]
I've run it on a number of machines: for example
- MacBook Pro (Core i7)
- Mac Mini (Core i5)
- Dell Windows gaming PC
- Dell Linux PC

CPU load will typically be noticeable while the video is decoding - not sure on exact percentages

**Comment by RSATom** [comment]
i.e. more than 10-20% ? Right?

**Comment by tmarrinan** [comment]
Yes

**Comment by RSATom** [comment]
Thank you for info.
