### ISSUE TITLE
Getting RGB from YUV source

### ISSUE THREAD

**Issue by acgourley** [tmarrinan/node-demux#6]
I need to get the RGB888 values so that I can move these frames into some graphics packages inside node which expect that as input. After some research I see I can use libav's sws_context approach to do this. Is this what you would suggest? If not, do you see something easier? Thanks!

**Comment by tmarrinan** [comment]
Yes, this seems like a good approach (if needing RGB in the node server). Otherwise, I've used YUV buffers client-side in a browser and use a WebGL shader to do the conversion from YUV to RGB.
